### ISSUE TITLE
Extend implementation of the connector class according to the interface specification in BaseCloudConnector class to support vertical scaling IaaS actions

### ISSUE THREAD

**Issue by konstan** [CELAR/SlipStreamConnector-Okeanos#9]
See the corresponding interface definition in https://github.com/slipstream/SlipStreamClient/issues/102

**Comment by loverdos** [comment]
@konstan In IBaseCloudConnector.resize(), how do I know what kind of resize is requested (RAM, CPU or even both)?

**Comment by konstan** [comment]
Please check the body of the `resize()` I've provided the use the corresponding getters on NodeInstance.
```python
       # RAM in GB.
        ram = node_instance.get_ram()
        # Number of CPUs.
        cpu = node_instance.get_cpu()
```

**Comment by konstan** [comment]
or if T-shirt sizes are used
```python
       # In case cloud uses T-short sizes.
        instance_type = node_instance.get_instance_type()
```

**Comment by konstan** [comment]
I guess, the second is your case.

**Comment by konstan** [comment]
The idea is that you don't try to guess what has changed, you just pick what is given by the getters and request it to be applied.  Does it make sense?

**Comment by loverdos** [comment]
I think I need some more semantics on this: Will both getters return a value? What if only RAM is resized? Does the other getter return None ?

**Comment by konstan** [comment]
Lets group the getters.  

For Flexiant:
```
        # RAM in GB.
        ram = node_instance.get_ram()
        # Number of CPUs.
        cpu = node_instance.get_cpu()
```

For Okeanos:
```
       # In case cloud uses T-short sizes.
        instance_type = node_instance.get_instance_type()
```

Okeanos connector should never call `get_ram()/cpu()`.  

It will be up to the requester of the scaling action to define the T-shirt size according to the Decision Making Module request to scale up/down the CPU and/or RAM.  DMM itself or CELAR Orchestrator can maintain (or dynamically derive) a map of `CPU/RAM  => T-shirt sizes` according to cloud and adapt the change request to the closest T-shirt match. (See [1])  Then, CELAR Orchestrator (as the adaptor of the scaling action request between DMM and SS) will be calling `ss-scale-resize --instance-type <T-shirt-size>`.

For the reference on `ss-scale-*` commands: https://github.com/slipstream/SlipStreamClient/issues/103

If `get_instance_type()` returns `None`, you fail by raising `ExecutionException`.


[1].  We indeed could decide to use CPU/RAM directly in Okeanos as well, and search the closest T-shirt match in the connector's `resize()`.  However, IMHO this breaks the symmetry of initial T-shirt size based definition and the CPU/RAM based scaling.

Nothing is carved on stone (yet :)).  I'm waiting for suggestions as well.

**Comment by loverdos** [comment]
OK, I was totally unaware of "T-Shirt" sizes etc but I get the picture.

Yes, get_instance_type() makes sense for ~okeanos, since it combines CPU/RAM in flavours. There is one API call to resize a server: https://www.synnefo.org/docs/synnefo/latest/compute-api-guide.html#resize-server.

For this to work, get_instance_type() must return one of the existing ~okeanos flavours, meaning that the flavours must be stored somewhere in the system.

Let's proceed with get_instance_type() (or T-shirt as I have learned)

**Comment by konstan** [comment]
Great.  

Today I had a chat with Giannis and made him aware that the initial decision was to require T-shirt size to be provided from DMM+CELAR Orch.  He was OK with this.  We will see how this evolves.
